var pokemonData = [
  {
    nr:"1",
    naam:"Bulbasaur",
    type:"Gras/Gif",
    soort:"Zaad"
  },
  {
    nr:"2",
    naam:"Ivysaur",
    type:"Gras/Gif",
    soort:"Zaad"
  },
  {
    nr:"3",
    naam:"Venusaur",
    type:"Gras/Gif",
    soort:"Zaad"
  },
  {
    nr:"4",
    naam:"Charmander",
    type:"Vuur",
    soort:"Hagedis"
  },
  {
    nr:"5",
    naam:"Charmeleon",
    type:"Vuur",
    soort:"Vlam"
  },
  {
    nr:"6",
    naam:"Charizard",
    type:"Vuur/Vlieg",
    soort:"Vuurdraak"
  },
  {
    nr:"7",
    naam:"Squirtle",
    type:"Water",
    soort:"Kleine Schildpad"
  },
  {
    nr:"8",
    naam:"Wartortle",
    type:"Water",
    soort:"Schildpad"
  },
  {
    nr:"9",
    naam:"Blastoise",
    type:"Water",
    soort:"Schelpdier"
  },
  {
    nr:"10",
    naam:"Caterpie",
    type:"Insect",
    soort:"Rups"
  },
  {
    nr:"11",
    naam:"Metapod",
    type:"Insect",
    soort:"Cocon"
  },
  {
    nr:"12",
    naam:"Butterfree",
    type:"Insect/Vlieg",
    soort:"Vlinder"
  },
  {
    nr:"13",
    naam:"Weedle",
    type:"Insect/Gif",
    soort:"Harige Worm"
  },
  {
    nr:"14",
    naam:"Kakuna",
    type:"Insect/Gif",
    soort:"Cocon"
  },
  {
    nr:"15",
    naam:"Beedrill",
    type:"Insect/Gif",
    soort:"Gifbij"
  },
  {
    nr:"16",
    naam:"Pidgey",
    type:"Gewoon/Vlieg",
    soort:"Kleine Vogel"
  },
  {
    nr:"17",
    naam:"Pidgeotto",
    type:"Gewoon/Vlieg",
    soort:"Vogel"
  },
  {
    nr:"18",
    naam:"Pidgeot",
    type:"Gewoon/Vlieg",
    soort:"Vogel"
  },
  {
    nr:"19",
    naam:"Rattata",
    type:"Gewoon",
    soort:"Rat"
  },
  {
    nr:"20",
    naam:"Raticate",
    type:"Gewoon",
    soort:"Rat"
  },
  {
    nr:"21",
    naam:"Spearow",
    type:"Gewoon/Vlieg",
    soort:"Kleine Vogel"
  },
  {
    nr:"22",
    naam:"Fearow",
    type:"Gewoon/Vlieg",
    soort:"Grote Vogel"
  },
  {
    nr:"23",
    naam:"Ekans",
    type:"Gif",
    soort:"Slang"
  },
  {
    nr:"24",
    naam:"Arbok",
    type:"Gif",
    soort:"Cobra"
  },
  {
    nr:"25",
    naam:"Pikachu",
    type:"Elektro",
    soort:"Muis"
  },
  {
    nr:"26",
    naam:"Raichu",
    type:"Elektro",
    soort:"Muis"
  },
  {
    nr:"27",
    naam:"Sandshrew",
    type:"Grond",
    soort:"Gordeldier"
  },
  {
    nr:"28",
    naam:"Sandslash",
    type:"Grond",
    soort:"Gordeldier"
  },
  {
    nr:"29",
    naam:"Nidoran ?",
    type:"Gif",
    soort:"Gifstekel"
  },
  {
    nr:"30",
    naam:"Nidorina",
    type:"Gif",
    soort:"Gifstekel"
  },
  {
    nr:"31",
    naam:"Nidoqueen",
    type:"Gif/Grond",
    soort:"Boor"
  },
  {
    nr:"32",
    naam:"Nidoran ?",
    type:"Gif",
    soort:"Gifstekel"
  },
  {
    nr:"33",
    naam:"Nidorino",
    type:"Gif",
    soort:"Gifstekel"
  },
  {
    nr:"34",
    naam:"Nidoking",
    type:"Gif/Grond",
    soort:"Boor"
  },
  {
    nr:"35",
    naam:"Clefairy",
    type:"Gewoon",
    soort:"Elf"
  },
  {
    nr:"36",
    naam:"Clefable",
    type:"Gewoon",
    soort:"Elf"
  },
  {
    nr:"37",
    naam:"Vulpix",
    type:"Vuur",
    soort:"Vos"
  },
  {
    nr:"38",
    naam:"Ninetales",
    type:"Vuur",
    soort:"Veel Staarten"
  },
  {
    nr:"39",
    naam:"Jigglypuff",
    type:"Gewoon",
    soort:"Ballon"
  },
  {
    nr:"40",
    naam:"Wigglytuff",
    type:"Gewoon",
    soort:"Ballon"
  },
  {
    nr:"41",
    naam:"Zubat",
    type:"Gif/Vlieg",
    soort:"Vleermuis"
  },
  {
    nr:"42",
    naam:"Golbat",
    type:"Gif/Vlieg",
    soort:"Vleermuis"
  },
  {
    nr:"43",
    naam:"Oddish",
    type:"Gras/Gif",
    soort:"Onkruid"
  },
  {
    nr:"44",
    naam:"Gloom",
    type:"Gras/Gif",
    soort:"Onkruid"
  },
  {
    nr:"45",
    naam:"Vileplume",
    type:"Gras/Gif",
    soort:"Bloem"
  },
  {
    nr:"46",
    naam:"Paras",
    type:"Insect/Gras",
    soort:"Paddenstoel"
  },
  {
    nr:"47",
    naam:"Parasect",
    type:"Insect/Gras",
    soort:"Paddenstoel"
  },
  {
    nr:"48",
    naam:"Venonat",
    type:"Insect/Gif",
    soort:"Insect"
  },
  {
    nr:"49",
    naam:"Venomoth",
    type:"Insect/Gif",
    soort:"Gifmot"
  },
  {
    nr:"50",
    naam:"Diglett",
    type:"Grond",
    soort:"Mol"
  },
  {
    nr:"51",
    naam:"Dugtrio",
    type:"Grond",
    soort:"Mol"
  },
  {
    nr:"52",
    naam:"Meowth",
    type:"Gewoon",
    soort:"Krabbende Kat"
  },
  {
    nr:"53",
    naam:"Persian",
    type:"Gewoon",
    soort:"Chique Kat"
  },
  {
    nr:"54",
    naam:"Psyduck",
    type:"Water",
    soort:"Eend"
  },
  {
    nr:"55",
    naam:"Golduck",
    type:"Water",
    soort:"Eend"
  },
  {
    nr:"56",
    naam:"Mankey",
    type:"Vecht",
    soort:"Varkensaap"
  },
  {
    nr:"57",
    naam:"Primeape",
    type:"Vecht",
    soort:"Varkensaap"
  },
  {
    nr:"58",
    naam:"Growlithe",
    type:"Vuur",
    soort:"Puppy"
  },
  {
    nr:"59",
    naam:"Arcanine",
    type:"Vuur",
    soort:"Legendarisch"
  },
  {
    nr:"60",
    naam:"Poliwag",
    type:"Water",
    soort:"Kikkervisje"
  },
  {
    nr:"61",
    naam:"Poliwhirl",
    type:"Water",
    soort:"Kikkervisje"
  },
  {
    nr:"62",
    naam:"Poliwrath",
    type:"Water/Vecht",
    soort:"Kikkervisje"
  },
  {
    nr:"63",
    naam:"Abra",
    type:"Psycho",
    soort:"Helderziende"
  },
  {
    nr:"64",
    naam:"Kadabra",
    type:"Psycho",
    soort:"Helderziende"
  },
  {
    nr:"65",
    naam:"Alakazam",
    type:"Psycho",
    soort:"Helderziende"
  },
  {
    nr:"66",
    naam:"Machop",
    type:"Vecht",
    soort:"Superkracht"
  },
  {
    nr:"67",
    naam:"Machoke",
    type:"Vecht",
    soort:"Superkracht"
  },
  {
    nr:"68",
    naam:"Machamp",
    type:"Vecht",
    soort:"Superkracht"
  },
  {
    nr:"69",
    naam:"Bellsprout",
    type:"Gras/Gif",
    soort:"Bloem"
  },
  {
    nr:"70",
    naam:"Weepinbell",
    type:"Gras/Gif",
    soort:"Vliegenvanger"
  },
  {
    nr:"71",
    naam:"Victreebel",
    type:"Gras/Gif",
    soort:"Vliegenvanger"
  },
  {
    nr:"72",
    naam:"Tentacool",
    type:"Water/Gif",
    soort:"Kwal"
  },
  {
    nr:"73",
    naam:"Tentacruel",
    type:"Water/Gif",
    soort:"Kwal"
  },
  {
    nr:"74",
    naam:"Geodude",
    type:"Steen/Grond",
    soort:"Rots"
  },
  {
    nr:"75",
    naam:"Graveler",
    type:"Steen/Grond",
    soort:"Rots"
  },
  {
    nr:"76",
    naam:"Golem",
    type:"Steen/Grond",
    soort:"Megaton"
  },
  {
    nr:"77",
    naam:"Ponyta",
    type:"Vuur",
    soort:"Vuurpaard"
  },
  {
    nr:"78",
    naam:"Rapidash",
    type:"Vuur",
    soort:"Vuureenhoorn"
  },
  {
    nr:"79",
    naam:"Slowpoke",
    type:"Water/Psycho",
    soort:"Langzaam"
  },
  {
    nr:"80",
    naam:"Slowbro",
    type:"Water/Psycho",
    soort:"Heremietkreeft"
  },
  {
    nr:"81",
    naam:"Magnemite",
    type:"Elektro/Staal",
    soort:"Magneet"
  },
  {
    nr:"82",
    naam:"Magneton",
    type:"Elektro/Staal",
    soort:"Magneet"
  },
  {
    nr:"83",
    naam:"Farfetch'd",
    type:"Gewoon/Vlieg",
    soort:"Wilde Eend"
  },
  {
    nr:"84",
    naam:"Doduo",
    type:"Gewoon/Vlieg",
    soort:"Tweelingvogel"
  },
  {
    nr:"85",
    naam:"Dodrio",
    type:"Gewoon/Vlieg",
    soort:"Drielingvogel"
  },
  {
    nr:"86",
    naam:"Seel",
    type:"Water/IJs",
    soort:"Zeeleeuw"
  },
  {
    nr:"87",
    naam:"Dewgong",
    type:"Water/IJs",
    soort:"Zeeleeuw"
  },
  {
    nr:"88",
    naam:"Grimer",
    type:"Gif",
    soort:"Blubber"
  },
  {
    nr:"89",
    naam:"Muk",
    type:"Gif",
    soort:"Blubber"
  },
  {
    nr:"90",
    naam:"Shellder",
    type:"Water",
    soort:"Tweekleppig"
  },
  {
    nr:"91",
    naam:"Cloyster",
    type:"Water/IJs",
    soort:"Tweekleppig"
  },
  {
    nr:"92",
    naam:"Gastly",
    type:"Spook/Gif",
    soort:"Gas"
  },
  {
    nr:"93",
    naam:"Haunter",
    type:"Spook/Gif",
    soort:"Gas"
  },
  {
    nr:"94",
    naam:"Gengar",
    type:"Spook/Gif",
    soort:"Schaduw"
  },
  {
    nr:"95",
    naam:"Onix",
    type:"Steen/Grond",
    soort:"Rotsslang"
  },
  {
    nr:"96",
    naam:"Drowzee",
    type:"Psycho",
    soort:"Hypnose"
  },
  {
    nr:"97",
    naam:"Hypno",
    type:"Psycho",
    soort:"Hypnose"
  },
  {
    nr:"98",
    naam:"Krabby",
    type:"Water",
    soort:"Rivierkreeft"
  },
  {
    nr:"99",
    naam:"Kingler",
    type:"Water",
    soort:"Schaar"
  },
  {
    nr:"100",
    naam:"Voltorb",
    type:"Elektro",
    soort:"Bal"
  },
  {
    nr:"101",
    naam:"Electrode",
    type:"Elektro",
    soort:"Explosief"
  },
  {
    nr:"102",
    naam:"Exeggcute",
    type:"Gras/Psycho",
    soort:"Ei"
  },
  {
    nr:"103",
    naam:"Exeggutor",
    type:"Gras/Psycho",
    soort:"Kokosnoot"
  },
  {
    nr:"104",
    naam:"Cubone",
    type:"Grond",
    soort:"Eenzaam"
  },
  {
    nr:"105",
    naam:"Marowak",
    type:"Grond",
    soort:"Botbewaarder"
  },
  {
    nr:"106",
    naam:"Hitmonlee",
    type:"Vecht",
    soort:"Schoppend"
  },
  {
    nr:"107",
    naam:"Hitmonchan",
    type:"Vecht",
    soort:"Stompend"
  },
  {
    nr:"108",
    naam:"Lickitung",
    type:"Gewoon",
    soort:"Likkend"
  },
  {
    nr:"109",
    naam:"Koffing",
    type:"Gif",
    soort:"Gifgas"
  },
  {
    nr:"110",
    naam:"Weezing",
    type:"Gif",
    soort:"Gifgas"
  },
  {
    nr:"111",
    naam:"Rhyhorn",
    type:"Grond/Steen",
    soort:"Spijker"
  },
  {
    nr:"112",
    naam:"Rhydon",
    type:"Grond/Steen",
    soort:"Boor"
  },
  {
    nr:"113",
    naam:"Chansey",
    type:"Gewoon",
    soort:"Zuster"
  },
  {
    nr:"114",
    naam:"Tangela",
    type:"Gras",
    soort:"Klimplant"
  },
  {
    nr:"115",
    naam:"Kangaskhan",
    type:"Gewoon",
    soort:"Ouder"
  },
  {
    nr:"116",
    naam:"Horsea",
    type:"Water",
    soort:"Draak"
  },
  {
    nr:"117",
    naam:"Seadra",
    type:"Water",
    soort:"Draak"
  },
  {
    nr:"118",
    naam:"Goldeen",
    type:"Water",
    soort:"Goudvis"
  },
  {
    nr:"119",
    naam:"Seaking",
    type:"Water",
    soort:"Goudvis"
  },
  {
    nr:"120",
    naam:"Staryu",
    type:"Water",
    soort:"Zeester"
  },
  {
    nr:"121",
    naam:"Starmie",
    type:"Water/Psycho",
    soort:"Zeester"
  },
  {
    nr:"122",
    naam:"Mr. Mime",
    type:"Psycho",
    soort:"Barrière"
  },
  {
    nr:"123",
    naam:"Scyther",
    type:"Insect/Vlieg",
    soort:"Bidsprinkhaan"
  },
  {
    nr:"124",
    naam:"Jynx",
    type:"IJs/Psycho",
    soort:"Menselijk Gevormd"
  },
  {
    nr:"125",
    naam:"Electabuzz",
    type:"Elektro",
    soort:"Elektrisch"
  },
  {
    nr:"126",
    naam:"Magmar",
    type:"Vuur",
    soort:"Vulkaan"
  },
  {
    nr:"127",
    naam:"Pinsir",
    type:"Insect",
    soort:"Vliegend Hert"
  },
  {
    nr:"128",
    naam:"Tauros",
    type:"Gewoon",
    soort:"Wilde Stier"
  },
  {
    nr:"129",
    naam:"Magikarp",
    type:"Water",
    soort:"Vis"
  },
  {
    nr:"130",
    naam:"Gyarados",
    type:"Water/Vlieg",
    soort:"Water Slang"
  },
  {
    nr:"131",
    naam:"Lapras",
    type:"Water/IJs",
    soort:"Transport"
  },
  {
    nr:"132",
    naam:"Ditto",
    type:"Gewoon",
    soort:"Transformatie"
  },
  {
    nr:"133",
    naam:"Eevee",
    type:"Gewoon",
    soort:"Evolutie"
  },
  {
    nr:"134",
    naam:"Vaporeon",
    type:"Water",
    soort:"Water"
  },
  {
    nr:"135",
    naam:"Jolteon",
    type:"Elektro",
    soort:"Bliksem"
  },
  {
    nr:"136",
    naam:"Flareon",
    type:"Vuur",
    soort:"Vlam"
  },
  {
    nr:"137",
    naam:"Porygon",
    type:"Gewoon",
    soort:"Virtueel"
  },
  {
    nr:"138",
    naam:"Omanyte",
    type:"Steen/Water",
    soort:"Spiraal"
  },
  {
    nr:"139",
    naam:"Omastar",
    type:"Steen/Water",
    soort:"Spiraal"
  },
  {
    nr:"140",
    naam:"Kabuto",
    type:"Steen/Water",
    soort:"Schelpdier"
  },
  {
    nr:"141",
    naam:"Kabutops",
    type:"Steen/Water",
    soort:"Schelpdier"
  },
  {
    nr:"142",
    naam:"Aerodactyl",
    type:"Steen/Vlieg",
    soort:"Fossiel"
  },
  {
    nr:"143",
    naam:"Snorlax",
    type:"Gewoon",
    soort:"Slapend"
  },
  {
    nr:"144",
    naam:"Articuno",
    type:"IJs/Vlieg",
    soort:"Bevriezing"
  },
  {
    nr:"145",
    naam:"Zapdos",
    type:"Elektrisch/Vlieg",
    soort:"Elektrisch"
  },
  {
    nr:"146",
    naam:"Moltres",
    type:"Vuur/Vlieg",
    soort:"Vlam"
  },
  {
    nr:"147",
    naam:"Dratini",
    type:"Draak",
    soort:"Draak"
  },
  {
    nr:"148",
    naam:"Dragonair",
    type:"Draak",
    soort:"Draak"
  },
  {
    nr:"149",
    naam:"Dragonite",
    type:"Draak/Vlieg",
    soort:"Draak"
  },
  {
    nr:"150",
    naam:"Mewtwo",
    type:"Psycho",
    soort:"Genetisch"
  },
  {
    nr:"151",
    naam:"Mew",
    type:"Psycho",
    soort:"Nieuwe soort"
  },
  {
    nr:"152",
    naam:"Chikorita",
    type:"Gras",
    soort:"Blad"
  },
  {
    nr:"153",
    naam:"Bayleef",
    type:"Gras",
    soort:"Blad"
  },
  {
    nr:"154",
    naam:"Meganium",
    type:"Gras",
    soort:"Plant"
  },
  {
    nr:"155",
    naam:"Cyndaquil",
    type:"Vuur",
    soort:"Vuurmol"
  },
  {
    nr:"156",
    naam:"Quilava",
    type:"Vuur",
    soort:"Vulkaan"
  },
  {
    nr:"157",
    naam:"Typhlosion",
    type:"Vuur",
    soort:"Vulkaan"
  },
  {
    nr:"158",
    naam:"Totodile",
    type:"Water",
    soort:"Grote Kaak"
  },
  {
    nr:"159",
    naam:"Croconaw",
    type:"Water",
    soort:"Grote Kaak"
  },
  {
    nr:"160",
    naam:"Feraligatr",
    type:"Water",
    soort:"Grote Kaak"
  },
  {
    nr:"161",
    naam:"Sentret",
    type:"Gewoon",
    soort:"Verkenner"
  },
  {
    nr:"162",
    naam:"Furret",
    type:"Gewoon",
    soort:"Lang Lichaam"
  },
  {
    nr:"163",
    naam:"Hoothoot",
    type:"Gewoon/Vlieg",
    soort:"Uil"
  },
  {
    nr:"164",
    naam:"Noctowl",
    type:"Gewoon/Vlieg",
    soort:"Uil"
  },
  {
    nr:"165",
    naam:"Ledyba",
    type:"Insect/Vlieg",
    soort:"Vijf Stippen"
  },
  {
    nr:"166",
    naam:"Ledian",
    type:"Insect/Vlieg",
    soort:"Vijf Stippen"
  },
  {
    nr:"167",
    naam:"Spinarak",
    type:"Insect/Gif",
    soort:"Spuugdraad"
  },
  {
    nr:"168",
    naam:"Ariados",
    type:"Insect/Gif",
    soort:"Langpoot"
  },
  {
    nr:"169",
    naam:"Crobat",
    type:"Gif/Vlieg",
    soort:"Vleermuis"
  },
  {
    nr:"170",
    naam:"Chinchou",
    type:"Water/Elektro",
    soort:"Hengel"
  },
  {
    nr:"171",
    naam:"Lanturn",
    type:"Water/Elektro",
    soort:"Licht"
  },
  {
    nr:"172",
    naam:"Pichu",
    type:"Elektro",
    soort:"Kleine Muis"
  },
  {
    nr:"173",
    naam:"Cleffa",
    type:"Gewoon",
    soort:"Stervormig"
  },
  {
    nr:"174",
    naam:"Igglybuff",
    type:"Gewoon",
    soort:"Ballon"
  },
  {
    nr:"175",
    naam:"Togepi",
    type:"Gewoon",
    soort:"half ei"
  },
  {
    nr:"176",
    naam:"Togetic",
    type:"Gewoon/Vlieg",
    soort:"Geluk"
  },
  {
    nr:"177",
    naam:"Natu",
    type:"Psycho/Vlieg",
    soort:"Kleine Vogel"
  },
  {
    nr:"178",
    naam:"Xatu",
    type:"Psycho/Vlieg",
    soort:"Mystiek"
  },
  {
    nr:"179",
    naam:"Mareep",
    type:"Elektro",
    soort:"Wol"
  },
  {
    nr:"180",
    naam:"Flaaffy",
    type:"Elektro",
    soort:"Wol"
  },
  {
    nr:"181",
    naam:"Ampharos",
    type:"Elektro",
    soort:"Licht"
  },
  {
    nr:"182",
    naam:"Bellossom",
    type:"Gras",
    soort:"Bloem"
  },
  {
    nr:"183",
    naam:"Marril",
    type:"Water",
    soort:"Watermuis"
  },
  {
    nr:"184",
    naam:"Azumarill",
    type:"Water",
    soort:"Waterhaas"
  },
  {
    nr:"185",
    naam:"Sudowoodo",
    type:"Steen",
    soort:"Imitatie"
  },
  {
    nr:"186",
    naam:"Politoed",
    type:"Water",
    soort:"Kikker"
  },
  {
    nr:"187",
    naam:"Hoppip",
    type:"Gras/Vlieg",
    soort:"Katoenplant"
  },
  {
    nr:"188",
    naam:"Skiploom",
    type:"Gras/Vlieg",
    soort:"Katoenplant"
  },
  {
    nr:"189",
    naam:"Jumpluff",
    type:"Gras/Vlieg",
    soort:"Katoenplant"
  },
  {
    nr:"190",
    naam:"Aipom",
    type:"Gewoon",
    soort:"Lange Staart"
  },
  {
    nr:"191",
    naam:"Sunkern",
    type:"Gras",
    soort:"Zaad"
  },
  {
    nr:"192",
    naam:"Sunflora",
    type:"Gras",
    soort:"Zonnebloem"
  },
  {
    nr:"193",
    naam:"Yanma",
    type:"Insect/Vlieg",
    soort:"Ruime Vleugel"
  },
  {
    nr:"194",
    naam:"Wooper",
    type:"Water",
    soort:"Watervis"
  },
  {
    nr:"195",
    naam:"Quagsire",
    type:"Water/Grond",
    soort:"Watervis"
  },
  {
    nr:"196",
    naam:"Espeon",
    type:"Psycho",
    soort:"Zonlicht"
  },
  {
    nr:"197",
    naam:"Umbreon",
    type:"Donker",
    soort:"Maanlicht"
  },
  {
    nr:"198",
    naam:"Murkrow",
    type:"Donker/Vlieg",
    soort:"kraai"
  },
  {
    nr:"199",
    naam:"Slowking",
    type:"Water/Psycho",
    soort:"Koninklijk"
  },
  {
    nr:"200",
    naam:"Misdreavus",
    type:"Spook",
    soort:"Gil"
  },
  {
    nr:"201",
    naam:"Unown",
    type:"Psycho",
    soort:"Symbool"
  },
  {
    nr:"202",
    naam:"Wobbuffet",
    type:"Psycho",
    soort:"Geduld"
  },
  {
    nr:"203",
    naam:"Girafarig",
    type:"Gewoon/Psycho",
    soort:"Lange Nek"
  },
  {
    nr:"204",
    naam:"Pineco",
    type:"Insect",
    soort:"Hangworm"
  },
  {
    nr:"205",
    naam:"Forretress",
    type:"Insect/Staal",
    soort:"Hangworm"
  },
  {
    nr:"206",
    naam:"Dunsparce",
    type:"Gewoon",
    soort:"Land Slang"
  },
  {
    nr:"207",
    naam:"Gligar",
    type:"Grond/Vlieg",
    soort:"Vliegende Schorpioen"
  },
  {
    nr:"208",
    naam:"Steelix",
    type:"Staal/Grond",
    soort:"IJzeren Slang"
  },
  {
    nr:"209",
    naam:"Snubbull",
    type:"Gewoon",
    soort:"Elf"
  },
  {
    nr:"210",
    naam:"Granbull",
    type:"Gewoon",
    soort:"bulldog"
  },
  {
    nr:"211",
    naam:"Qwilfish",
    type:"Water/Gif",
    soort:"Ballonvis"
  },
  {
    nr:"212",
    naam:"Scizor",
    type:"Insect/Staal",
    soort:"Schaar"
  },
  {
    nr:"213",
    naam:"Shuckle",
    type:"Insect/Steen",
    soort:"Vorm"
  },
  {
    nr:"214",
    naam:"Heracross",
    type:"Insect/Vecht",
    soort:"Hoorn"
  },
  {
    nr:"215",
    naam:"Sneasel",
    type:"Donker/IJs",
    soort:"Scherpe Klauw"
  },
  {
    nr:"216",
    naam:"Teddiursa",
    type:"Gewoon",
    soort:"Kleine Beer"
  },
  {
    nr:"217",
    naam:"Ursaring",
    type:"Gewoon",
    soort:"Hibernator"
  },
  {
    nr:"218",
    naam:"Slugma",
    type:"Vuur",
    soort:"Lava naaktslak"
  },
  {
    nr:"219",
    naam:"Magcargo",
    type:"Vuur/Steen",
    soort:"Lava huisjesslak"
  },
  {
    nr:"220",
    naam:"Swinub",
    type:"IJs/Grond",
    soort:"Varken"
  },
  {
    nr:"221",
    naam:"Piloswine",
    type:"IJs/Grond",
    soort:"Zwijn"
  },
  {
    nr:"222",
    naam:"Corsola",
    type:"Water/Steen",
    soort:"Koraal"
  },
  {
    nr:"223",
    naam:"Remoraid",
    type:"Water",
    soort:"Jet"
  },
  {
    nr:"224",
    naam:"Octillery",
    type:"Water",
    soort:"octopus"
  },
  {
    nr:"225",
    naam:"Delibird",
    type:"IJs/Vlieg",
    soort:"Levering"
  },
  {
    nr:"226",
    naam:"Mantine",
    type:"Water",
    soort:"Kite"
  },
  {
    nr:"227",
    naam:"Skarmory",
    type:"Staal/Vlieg",
    soort:"Stalen Vogel"
  },
  {
    nr:"228",
    naam:"Houndour",
    type:"Donker/Vuur",
    soort:"Donker"
  },
  {
    nr:"229",
    naam:"Houndoom",
    type:"Donker/Vuur",
    soort:"Donker"
  },
  {
    nr:"230",
    naam:"Kingdra",
    type:"Water/Draak",
    soort:"Draak"
  },
  {
    nr:"231",
    naam:"Phanpy",
    type:"Grond",
    soort:"Lange Neus"
  },
  {
    nr:"232",
    naam:"Donphan",
    type:"Grond",
    soort:"Pantser"
  },
  {
    nr:"233",
    naam:"Porygon2",
    type:"Gewoon",
    soort:"Virtueel"
  },
  {
    nr:"234",
    naam:"Stantler",
    type:"Gewoon",
    soort:"hert"
  },
  {
    nr:"235",
    naam:"Smeargle",
    type:"Gewoon",
    soort:"Schilder"
  },
  {
    nr:"236",
    naam:"Tyrogue",
    type:"Vecht",
    soort:"Handgemeen"
  },
  {
    nr:"237",
    naam:"Hitmontop",
    type:"Vecht",
    soort:"Handenstand"
  },
  {
    nr:"238",
    naam:"Smoochum",
    type:"IJs/Psycho",
    soort:"Kus"
  },
  {
    nr:"239",
    naam:"Elekid",
    type:"Elektro",
    soort:"Elektrisch"
  },
  {
    nr:"240",
    naam:"Magby",
    type:"Vuur",
    soort:"Vuurspuwer"
  },
  {
    nr:"241",
    naam:"Miltank",
    type:"Gewoon",
    soort:"Melkkoe"
  },
  {
    nr:"242",
    naam:"Blissey",
    type:"Gewoon",
    soort:"Gelukkig"
  },
  {
    nr:"243",
    naam:"Raikou",
    type:"Elektro",
    soort:"Donder"
  },
  {
    nr:"244",
    naam:"Entei",
    type:"Vuur",
    soort:"Vulkaan"
  },
  {
    nr:"245",
    naam:"Suicune",
    type:"Water",
    soort:"Aurora"
  },
  {
    nr:"246",
    naam:"Larvitar",
    type:"Steen/Grond",
    soort:"Stenen Lichaam"
  },
  {
    nr:"247",
    naam:"Pupitar",
    type:"Steen/Grond",
    soort:"Harde Schild"
  },
  {
    nr:"248",
    naam:"Tyranitar",
    type:"Steen/Donker",
    soort:"Pantser"
  },
  {
    nr:"249",
    naam:"Lugia",
    type:"Psycho/Vlieg",
    soort:"oceaan"
  },
  {
    nr:"250",
    naam:"Ho-oh",
    type:"Vuur/Vlieg",
    soort:"Regenboog"
  },
  {
    nr:"251",
    naam:"Celebi",
    type:"Psycho/Gras",
    soort:"Tijdreis"
  },
  {
    nr:"252",
    naam:"Treecko",
    type:"Gras",
    soort:"Hout Gekko"
  },
  {
    nr:"253",
    naam:"Grovyle",
    type:"Gras",
    soort:"Hout Gekko"
  },
  {
    nr:"254",
    naam:"Sceptile",
    type:"Gras",
    soort:"Bos"
  },
  {
    nr:"255",
    naam:"Torchic",
    type:"Vuur",
    soort:"Kuiken"
  },
  {
    nr:"256",
    naam:"Combusken",
    type:"Vuur/Vecht",
    soort:"Jonge Haan"
  },
  {
    nr:"257",
    naam:"Blaziken",
    type:"Vuur/Vecht",
    soort:"Uitbarsting"
  },
  {
    nr:"258",
    naam:"Mudkip",
    type:"Water",
    soort:"Moddervis"
  },
  {
    nr:"259",
    naam:"Marshtomp",
    type:"Water/Grond",
    soort:"Moddervis"
  },
  {
    nr:"260",
    naam:"Swampert",
    type:"Water/Grond",
    soort:"Moddervis"
  },
  {
    nr:"261",
    naam:"Poochyena",
    type:"Donker",
    soort:"Wolf"
  },
  {
    nr:"262",
    naam:"Mightyena",
    type:"Donker",
    soort:"Wolf"
  },
  {
    nr:"263",
    naam:"Zigzagoon",
    type:"Gewoon",
    soort:"Kleine Wasbeer"
  },
  {
    nr:"264",
    naam:"Linoone",
    type:"Gewoon",
    soort:"Stormloop"
  },
  {
    nr:"265",
    naam:"Wurmple",
    type:"Insect",
    soort:"Worm"
  },
  {
    nr:"266",
    naam:"Silcoon",
    type:"Insect",
    soort:"Cocon"
  },
  {
    nr:"267",
    naam:"Beautifly",
    type:"Gewoon/Vlieg",
    soort:"Vlinder"
  },
  {
    nr:"268",
    naam:"Cascoon",
    type:"Insect",
    soort:"Cocon"
  },
  {
    nr:"269",
    naam:"Dustox",
    type:"Insect/Gif",
    soort:"Gifmot"
  },
  {
    nr:"270",
    naam:"Lotad",
    type:"Water/Gras",
    soort:"Waterplant"
  },
  {
    nr:"271",
    naam:"Lombre",
    type:"Water/Gras",
    soort:"Jolly"
  },
  {
    nr:"272",
    naam:"Ludicolo",
    type:"Water/Gras",
    soort:"Onbezorgd"
  },
  {
    nr:"273",
    naam:"Seedot",
    type:"Gras",
    soort:"Eikel"
  },
  {
    nr:"274",
    naam:"Nuzleaf",
    type:"Gras/Donker",
    soort:"Wily"
  },
  {
    nr:"275",
    naam:"Shiftry",
    type:"Gras/Donker",
    soort:"Wickid"
  },
  {
    nr:"276",
    naam:"Taillow",
    type:"Gewoon/Vlieg",
    soort:"Kleine Zwaluw"
  },
  {
    nr:"277",
    naam:"Swellow",
    type:"Gewoon/Vlieg",
    soort:"Zwaluw"
  },
  {
    nr:"278",
    naam:"Wingull",
    type:"Water/Vlieg",
    soort:"Zeemeeuw"
  },
  {
    nr:"279",
    naam:"Pelipper",
    type:"Water/vlieg",
    soort:"Watervogel"
  },
  {
    nr:"280",
    naam:"Ralts",
    type:"Psycho",
    soort:"Voelen"
  },
  {
    nr:"281",
    naam:"Kirlia",
    type:"Psycho",
    soort:"Emotie"
  },
  {
    nr:"282",
    naam:"Gardevoir",
    type:"Psycho",
    soort:"Omhels"
  },
  {
    nr:"283",
    naam:"Surskit",
    type:"Insect/Water",
    soort:"Meerschaatser"
  },
  {
    nr:"284",
    naam:"Masquerain",
    type:"Insect/Vlieg",
    soort:"Oogbal"
  },
  {
    nr:"285",
    naam:"Shroomish",
    type:"Gras",
    soort:"Paddenstoel"
  },
  {
    nr:"286",
    naam:"Breloom",
    type:"Gras/Vecht",
    soort:"Paddenstoel"
  },
  {
    nr:"287",
    naam:"Slakoth",
    type:"Gewoon",
    soort:"Slacker"
  },
  {
    nr:"288",
    naam:"Vigoroth",
    type:"Gewoon",
    soort:"Wilde Aap"
  },
  {
    nr:"289",
    naam:"Slaking",
    type:"Gewoon",
    soort:"Lui"
  },
  {
    nr:"290",
    naam:"Nincada",
    type:"Insect/Grond",
    soort:"verdubbeller"
  },
  {
    nr:"291",
    naam:"Ninjask",
    type:"Insect/Vlieg",
    soort:"Ninja"
  },
  {
    nr:"292",
    naam:"Shedinja",
    type:"Insect/Spook",
    soort:"Loods"
  },
  {
    nr:"293",
    naam:"Whismur",
    type:"Gewoon",
    soort:"Fluisteren"
  },
  {
    nr:"294",
    naam:"Loudred",
    type:"Gewoon",
    soort:"Luide Stem"
  },
  {
    nr:"295",
    naam:"Exploud",
    type:"Gewoon",
    soort:"Luid Lawaai"
  },
  {
    nr:"296",
    naam:"Makuhita",
    type:"Vecht",
    soort:"Guts"
  },
  {
    nr:"297",
    naam:"Hariyama",
    type:"Vecht",
    soort:"Armduwen"
  },
  {
    nr:"298",
    naam:"Azurill",
    type:"Gewoon",
    soort:"Polka Bal"
  },
  {
    nr:"299",
    naam:"Nosepass",
    type:"Steen",
    soort:"Kompas/paas hoofd"
  },
  {
    nr:"300",
    naam:"Skitty",
    type:"Gewoon",
    soort:"Jong Katje"
  },
  {
    nr:"301",
    naam:"Delcatty",
    type:"Gewoon",
    soort:"Kat"
  },
  {
    nr:"302",
    naam:"Sableye",
    type:"Donker/Spook",
    soort:"Duisternis"
  },
  {
    nr:"303",
    naam:"Mawile",
    type:"Staal",
    soort:"Deceiver"
  },
  {
    nr:"304",
    naam:"Aron",
    type:"Staal/Steen",
    soort:"IJzeren Pantser"
  },
  {
    nr:"305",
    naam:"Lairon",
    type:"Staal/Steen",
    soort:"IJzeren Pantser"
  },
  {
    nr:"306",
    naam:"Aggron",
    type:"Staal/Steen",
    soort:"IJzeren Pantser"
  },
  {
    nr:"307",
    naam:"Meditite",
    type:"Vecht/Psycho",
    soort:"Meditatie"
  },
  {
    nr:"308",
    naam:"Medicham",
    type:"Vecht/Psycho",
    soort:"Meditatie"
  },
  {
    nr:"309",
    naam:"Electrike",
    type:"Elektro",
    soort:"Bliksem"
  },
  {
    nr:"310",
    naam:"Manectric",
    type:"Elektro",
    soort:"Lossing"
  },
  {
    nr:"311",
    naam:"Plusle",
    type:"Elektro",
    soort:"Aanmoedigen"
  },
  {
    nr:"312",
    naam:"Minun",
    type:"Elektro",
    soort:"Aanmoedigen"
  },
  {
    nr:"313",
    naam:"Volbeat",
    type:"Insect",
    soort:"Vuurvlieg"
  },
  {
    nr:"314",
    naam:"Illumise",
    type:"Insect",
    soort:"Vuurvlieg"
  },
  {
    nr:"315",
    naam:"Roselia",
    type:"Gras/Gif",
    soort:"Doorn"
  },
  {
    nr:"316",
    naam:"Gulpin",
    type:"Gif",
    soort:"Maag"
  },
  {
    nr:"317",
    naam:"Swalot",
    type:"Gif",
    soort:"Gifzak"
  },
  {
    nr:"318",
    naam:"Carvanha",
    type:"Water/Donker",
    soort:"Wild"
  },
  {
    nr:"319",
    naam:"Sharpedo",
    type:"Water/Duister",
    soort:"torpedo"
  },
  {
    nr:"320",
    naam:"Wailmer",
    type:"Water",
    soort:"Bal Walvis"
  },
  {
    nr:"321",
    naam:"Wailord",
    type:"Water",
    soort:"Vlot Walvis"
  },
  {
    nr:"322",
    naam:"Numel",
    type:"Vuur/Grond",
    soort:"Dromedaris"
  },
  {
    nr:"323",
    naam:"Camerupt",
    type:"Vuur/Grond",
    soort:"Uitbarsting"
  },
  {
    nr:"324",
    naam:"Torkoal",
    type:"Vuur",
    soort:"Kool"
  },
  {
    nr:"325",
    naam:"Spoink",
    type:"Psycho",
    soort:"Stuiter"
  },
  {
    nr:"326",
    naam:"Grumpig",
    type:"Psycho",
    soort:"Manipulatie"
  },
  {
    nr:"327",
    naam:"Spinda",
    type:"Gewoon",
    soort:"Gevlekte Panda"
  },
  {
    nr:"328",
    naam:"Trapinch",
    type:"Grond",
    soort:"Mierenput"
  },
  {
    nr:"329",
    naam:"Vibrava",
    type:"Grond/Draak",
    soort:"Vibratie"
  },
  {
    nr:"330",
    naam:"Flygon",
    type:"Grond/Draak",
    soort:"Mystiek"
  },
  {
    nr:"331",
    naam:"Cacnea",
    type:"Gras",
    soort:"Cactus"
  },
  {
    nr:"332",
    naam:"Cacturne",
    type:"Gras/Donker",
    soort:"Cactus"
  },
  {
    nr:"333",
    naam:"Swablu",
    type:"Gewoon/Vlieg",
    soort:"watten"
  },
  {
    nr:"334",
    naam:"Altaria",
    type:"Draak/Vlieg",
    soort:"Zoemend"
  },
  {
    nr:"335",
    naam:"Zangoose",
    type:"Gewoon",
    soort:"Kattenfret"
  },
  {
    nr:"336",
    naam:"Seviper",
    type:"Gif",
    soort:"Slangenkaak"
  },
  {
    nr:"337",
    naam:"Lunatone",
    type:"Steen/Psycho",
    soort:"Meteoor"
  },
  {
    nr:"338",
    naam:"Solrock",
    type:"Steen/Psycho",
    soort:"Meteoor"
  },
  {
    nr:"339",
    naam:"Barboach",
    type:"Water/Grond",
    soort:"Bakkebaarden"
  },
  {
    nr:"340",
    naam:"Whiscash",
    type:"Water/Grond",
    soort:"Bakkebaarden"
  },
  {
    nr:"341",
    naam:"Corphish",
    type:"Water",
    soort:"Schurk"
  },
  {
    nr:"342",
    naam:"Crawdaunt",
    type:"Water/Donker",
    soort:"Roque"
  },
  {
    nr:"343",
    naam:"Baltoy",
    type:"Grond/Psycho",
    soort:"Kleipop"
  },
  {
    nr:"344",
    naam:"Claydol",
    type:"Grond/Psycho",
    soort:"Kleipop"
  },
  {
    nr:"345",
    naam:"Lileep",
    type:"Steen/Gras",
    soort:"Zeelilly"
  },
  {
    nr:"346",
    naam:"Cradily",
    type:"Steen/Gras",
    soort:"Eendenmossel"
  },
  {
    nr:"347",
    naam:"Anorith",
    type:"Steen/Insect",
    soort:"Oude Garnaal"
  },
  {
    nr:"348",
    naam:"Armaldo",
    type:"Steen/Insect",
    soort:"Plaat"
  },
  {
    nr:"349",
    naam:"Feebas",
    type:"Water",
    soort:"Vis"
  },
  {
    nr:"350",
    naam:"Milotic",
    type:"Water",
    soort:"Offer"
  },
  {
    nr:"351",
    naam:"Castform",
    type:"Gewoon",
    soort:"Weer"
  },
  {
    nr:"352",
    naam:"Kecleon",
    type:"Gewoon",
    soort:"kameleon"
  },
  {
    nr:"353",
    naam:"Shuppet",
    type:"Spook",
    soort:"Pop"
  },
  {
    nr:"354",
    naam:"Banette",
    type:"Spook",
    soort:"Marionet"
  },
  {
    nr:"355",
    naam:"Duskull",
    type:"Spook",
    soort:"Requiem"
  },
  {
    nr:"356",
    naam:"Dusclops",
    type:"Spook",
    soort:"Wenk"
  },
  {
    nr:"357",
    naam:"Tropius",
    type:"Gras/Vlieg",
    soort:"Fruit"
  },
  {
    nr:"358",
    naam:"Chimecho",
    type:"Psycho",
    soort:"Windspel"
  },
  {
    nr:"359",
    naam:"Absol",
    type:"Donker",
    soort:"Ramp"
  },
  {
    nr:"360",
    naam:"Wynaut",
    type:"Psyycho",
    soort:"Helder"
  },
  {
    nr:"361",
    naam:"Snorunt",
    type:"IJs",
    soort:"Sneeuwhoed"
  },
  {
    nr:"362",
    naam:"Glalie",
    type:"IJs",
    soort:"Gezicht"
  },
  {
    nr:"363",
    naam:"Spheal",
    type:"IJs/Water",
    soort:"Klap"
  },
  {
    nr:"364",
    naam:"Sealeo",
    type:"IJs/Water",
    soort:"Rollende Bal"
  },
  {
    nr:"365",
    naam:"Walrein",
    type:"IJs/Water",
    soort:"IJsbreker"
  },
  {
    nr:"366",
    naam:"Clamperl",
    type:"Water",
    soort:"oester"
  },
  {
    nr:"367",
    naam:"Huntail",
    type:"Water",
    soort:"Diepzee"
  },
  {
    nr:"368",
    naam:"Gorebyss",
    type:"Water",
    soort:"Zuidzee"
  },
  {
    nr:"369",
    naam:"Relicanth",
    type:"Water/Steen",
    soort:"Longvity"
  },
  {
    nr:"370",
    naam:"Luvdisc",
    type:"Water",
    soort:"Liefdesschijf"
  },
  {
    nr:"371",
    naam:"Bagon",
    type:"Draak",
    soort:"Stenen Hoofd"
  },
  {
    nr:"372",
    naam:"Shelgon",
    type:"Draak",
    soort:"Duurzaamheid"
  },
  {
    nr:"373",
    naam:"Salamence",
    type:"Draak/Vlieg",
    soort:"Draak"
  },
  {
    nr:"374",
    naam:"Beldum",
    type:"Staal/Psycho",
    soort:"IJzeren Bal"
  },
  {
    nr:"375",
    naam:"Metang",
    type:"Staal/Psycho",
    soort:"IJzeren Klauw"
  },
  {
    nr:"376",
    naam:"Metagross",
    type:"Staal/Psycho",
    soort:"Stalen Benen"
  },
  {
    nr:"377",
    naam:"Regirock",
    type:"Steen",
    soort:"Rotspieken"
  },
  {
    nr:"378",
    naam:"Regice",
    type:"IJs",
    soort:"IJsberg"
  },
  {
    nr:"379",
    naam:"Registeel",
    type:"Staal",
    soort:"IJzerplaat"
  },
  {
    nr:"380",
    naam:"Latias",
    type:"Draak/Psycho",
    soort:"Eon"
  },
  {
    nr:"381",
    naam:"Latios",
    type:"Draak/Psycho",
    soort:"Eon"
  },
  {
    nr:"382",
    naam:"Kyogre",
    type:"Water",
    soort:"Overzees Basin"
  },
  {
    nr:"383",
    naam:"Groudon",
    type:"Grond",
    soort:"Continent"
  },
  {
    nr:"384",
    naam:"Rayquaza",
    type:"Draak/Vlieg",
    soort:"ozonlaag"
  },
  {
    nr:"385",
    naam:"Jirachi",
    type:"Staal/Psycho",
    soort:"Wens"
  },
  {
    nr:"386",
    naam:"Deoxys",
    type:"Psycho",
    soort:"DNA"
  },
  {
    nr:"387",
    naam:"Turtwig",
    type:"Gras",
    soort:"Klein Blad"
  },
  {
    nr:"388",
    naam:"Grotle",
    type:"Gras",
    soort:"Struik"
  },
  {
    nr:"389",
    naam:"Torterra",
    type:"Gras/grond",
    soort:"Land"
  },
  {
    nr:"390",
    naam:"Chimchar",
    type:"Vuur",
    soort:"Jonge Aap"
  },
  {
    nr:"391",
    naam:"Monferno",
    type:"Vuur/Vecht",
    soort:"Vechtaap"
  },
  {
    nr:"392",
    naam:"Infernape",
    type:"Vuur/Vecht",
    soort:"vuuraap"
  },
  {
    nr:"393",
    naam:"Piplup",
    type:"Water",
    soort:"Pinguïn"
  },
  {
    nr:"394",
    naam:"Prinplup",
    type:"Water",
    soort:"Pinguïn"
  },
  {
    nr:"395",
    naam:"Empoleon",
    type:"Water\\Staal",
    soort:"Keizerpinguïn"
  },
  {
    nr:"396",
    naam:"Starly",
    type:"Gewoon/Vlieg",
    soort:"spreeuw"
  },
  {
    nr:"397",
    naam:"Staravia",
    type:"Gewoon/Vlieg",
    soort:"Vogel"
  },
  {
    nr:"398",
    naam:"Staraptor",
    type:"Gewoon/Vlieg",
    soort:"Vogel"
  },
  {
    nr:"399",
    naam:"Bidoof",
    type:"Gewoon",
    soort:"Bever"
  },
  {
    nr:"400",
    naam:"Bibarel",
    type:"Gewoon/Water",
    soort:"Bever"
  },
  {
    nr:"401",
    naam:"Kricketot",
    type:"Insect",
    soort:"Kever"
  },
  {
    nr:"402",
    naam:"Kricketune",
    type:"Insect",
    soort:"Kever"
  },
  {
    nr:"403",
    naam:"Shinx",
    type:"Elektrisch",
    soort:"Flits"
  },
  {
    nr:"404",
    naam:"Luxio",
    type:"Elektrisch",
    soort:"Schok"
  },
  {
    nr:"405",
    naam:"Luxray",
    type:"Elektrisch",
    soort:"Lichtgevende Ogen"
  },
  {
    nr:"406",
    naam:"Budew",
    type:"Gras/Gif",
    soort:"Zaad"
  },
  {
    nr:"407",
    naam:"Roserade",
    type:"Gras/Gif",
    soort:"Doorn"
  },
  {
    nr:"408",
    naam:"Cranidos",
    type:"Steen",
    soort:"Kopstoot"
  },
  {
    nr:"409",
    naam:"Rampardos",
    type:"Steen",
    soort:"Pachycephalosaurus"
  },
  {
    nr:"410",
    naam:"Shieldon",
    type:"Steen/Staal",
    soort:"Schild"
  },
  {
    nr:"411",
    naam:"Bastiodon",
    type:"Steen/Staal",
    soort:"triceratops"
  },
  {
    nr:"412",
    naam:"Burmy",
    type:"Insect",
    soort:"HangWorm"
  },
  {
    nr:"413",
    naam:"Wormadam",
    type:"Insect/(Gras/Grond/Staal)",
    soort:"HangWorm"
  },
  {
    nr:"414",
    naam:"Mothim",
    type:"Insect/Vlieg",
    soort:"Mot"
  },
  {
    nr:"415",
    naam:"Combee",
    type:"Insect/Vlieg",
    soort:"Bij"
  },
  {
    nr:"416",
    naam:"Vespiquen",
    type:"Insect/Vlieg",
    soort:"Bijenkoningin"
  },
  {
    nr:"417",
    naam:"Pachirisu",
    type:"Elektrisch",
    soort:"Elektrische Eekhoorn"
  },
  {
    nr:"418",
    naam:"Buizel",
    type:"Water",
    soort:"Wezel"
  },
  {
    nr:"419",
    naam:"Floatzel",
    type:"Water",
    soort:"Zee-Wezel"
  },
  {
    nr:"420",
    naam:"Cherubi",
    type:"Gras",
    soort:"Bes"
  },
  {
    nr:"421",
    naam:"Cherrim",
    type:"Gras",
    soort:"Bloesem"
  },
  {
    nr:"422",
    naam:"Shellos",
    type:"Water",
    soort:"Zeeslak"
  },
  {
    nr:"423",
    naam:"Gastrodon",
    type:"Water/Grond",
    soort:"Zeeslak"
  },
  {
    nr:"424",
    naam:"Ambipom",
    type:"Normaal",
    soort:"Staart"
  },
  {
    nr:"425",
    naam:"Drifloon",
    type:"Spook/Vlieg",
    soort:"Ballon"
  },
  {
    nr:"426",
    naam:"Drifblim",
    type:"Spook/Vlieg",
    soort:"Ballon"
  },
  {
    nr:"427",
    naam:"Buneary",
    type:"Gewoon",
    soort:"Konijn"
  },
  {
    nr:"428",
    naam:"Lopunny",
    type:"Gewoon",
    soort:"Konijn"
  },
  {
    nr:"429",
    naam:"Mismagius",
    type:"Spook",
    soort:"Magische"
  },
  {
    nr:"430",
    naam:"Honchkrow",
    type:"Donker/Vlieg",
    soort:"Kraai"
  },
  {
    nr:"431",
    naam:"Glameow",
    type:"Gewoon",
    soort:"Kat"
  },
  {
    nr:"432",
    naam:"Purugly",
    type:"Gewoon",
    soort:"Vette Kat"
  },
  {
    nr:"433",
    naam:"Chingling",
    type:"Psychisch",
    soort:"Belletje"
  },
  {
    nr:"434",
    naam:"Stunky",
    type:"Gif/Donker",
    soort:"Stinkdier"
  },
  {
    nr:"435",
    naam:"Skuntank",
    type:"Gif/Donker",
    soort:"Stinkdier"
  },
  {
    nr:"436",
    naam:"Bronzor",
    type:"Staal/Psychisch",
    soort:"Brons"
  },
  {
    nr:"437",
    naam:"Bronzong",
    type:"Staal/Psychisch",
    soort:"Brons"
  },
  {
    nr:"438",
    naam:"Bonsly",
    type:"Steen",
    soort:"Bonzai"
  },
  {
    nr:"439",
    naam:"Mime Jr.",
    type:"Psychisch",
    soort:"Mime speler"
  },
  {
    nr:"440",
    naam:"Happiny",
    type:"Gewoon",
    soort:"Zuster"
  },
  {
    nr:"441",
    naam:"Chatot",
    type:"Gewoon/Vlieg",
    soort:"Muzieknoot"
  },
  {
    nr:"442",
    naam:"Spiritomb",
    type:"Spook/Donker",
    soort:"Verboden"
  },
  {
    nr:"443",
    naam:"Gible",
    type:"Draak/Grond",
    soort:"Landhaai"
  },
  {
    nr:"444",
    naam:"Gabite",
    type:"Draak/Grond",
    soort:"Grot"
  },
  {
    nr:"445",
    naam:"Garchomp",
    type:"Draak/Grond",
    soort:"Mach"
  },
  {
    nr:"446",
    naam:"Munchlax",
    type:"Gewoon",
    soort:"Grote eter"
  },
  {
    nr:"447",
    naam:"Riolu",
    type:"Vecht",
    soort:"Aura"
  },
  {
    nr:"448",
    naam:"Lucario",
    type:"Vecht/Staal",
    soort:"Aura"
  },
  {
    nr:"449",
    naam:"Hippopotas",
    type:"Grond",
    soort:"Nijlpaard"
  },
  {
    nr:"450",
    naam:"Hippowdon",
    type:"Grond",
    soort:"Nijlpaard"
  },
  {
    nr:"451",
    naam:"Skorupi",
    type:"Gif/Insect",
    soort:"Schorpioen"
  },
  {
    nr:"452",
    naam:"Drapion",
    type:"Gif/Donker",
    soort:"Schorpioen"
  },
  {
    nr:"453",
    naam:"Croagunk",
    type:"Gif/Vecht",
    soort:"Gif"
  },
  {
    nr:"454",
    naam:"Toxicroak",
    type:"Gif/Vecht",
    soort:"Gif"
  },
  {
    nr:"455",
    naam:"Carnivine",
    type:"Gras",
    soort:"Vliegenvanger"
  },
  {
    nr:"456",
    naam:"Finneon",
    type:"Water",
    soort:"Lichtvis"
  },
  {
    nr:"457",
    naam:"Lumineon",
    type:"Water",
    soort:"Lichtvis"
  },
  {
    nr:"458",
    naam:"Mantyke",
    type:"Water/Vlieg",
    soort:"rog"
  },
  {
    nr:"459",
    naam:"Snover",
    type:"IJs/Gras",
    soort:"Spar"
  },
  {
    nr:"460",
    naam:"Abomasnow",
    type:"IJs/Gras",
    soort:"Besneeuwde spar"
  },
  {
    nr:"461",
    naam:"Weavile",
    type:"Donker/IJs",
    soort:"Scherpe klauw"
  },
  {
    nr:"462",
    naam:"Magnezone",
    type:"Elektrisch/Staal",
    soort:"Magnetisch veld"
  },
  {
    nr:"463",
    naam:"Lickilicky",
    type:"Gewoon",
    soort:"Lange tong"
  },
  {
    nr:"464",
    naam:"Rhyperior",
    type:"Grond/Steen",
    soort:"Driller"
  },
  {
    nr:"465",
    naam:"Tangrowth",
    type:"Gras",
    soort:"Tentakel"
  },
  {
    nr:"466",
    naam:"Electivire",
    type:"Elektrisch",
    soort:"Donderschok"
  },
  {
    nr:"467",
    naam:"Magmortar",
    type:"Vuur",
    soort:"Uitbarsting"
  },
  {
    nr:"468",
    naam:"Togekiss",
    type:"Gewoon/Vlieg",
    soort:"Jubeleum"
  },
  {
    nr:"469",
    naam:"Yanmega",
    type:"Insect/Vlieg",
    soort:"Mensetende libel"
  },
  {
    nr:"470",
    naam:"Leafeon",
    type:"Gras",
    soort:"Natuur"
  },
  {
    nr:"471",
    naam:"Glaceon",
    type:"IJs",
    soort:"Verse Sneeuw"
  },
  {
    nr:"472",
    naam:"Gliscor",
    type:"Grond/Vlieg",
    soort:"Schorpioen"
  },
  {
    nr:"473",
    naam:"Mamoswine",
    type:"IJs/Grond",
    soort:"Slagtanden"
  },
  {
    nr:"474",
    naam:"Porygon-Z",
    type:"Gewoon",
    soort:"Virtueel"
  },
  {
    nr:"475",
    naam:"Gallade",
    type:"Psychisch/Vecht",
    soort:"Mes"
  },
  {
    nr:"476",
    naam:"Probopass",
    type:"Steen/Staal",
    soort:"Kompas/paas hoofd"
  },
  {
    nr:"477",
    naam:"Dusknoir",
    type:"Spook",
    soort:"Grijp"
  },
  {
    nr:"478",
    naam:"Froslass",
    type:"IJs/Spook",
    soort:"Sneeuw land"
  },
  {
    nr:"479",
    naam:"Rotom",
    type:"Elektrisch/Spook",
    soort:"Plasma"
  },
  {
    nr:"480",
    naam:"Uxie",
    type:"Psychisch",
    soort:"Wijsheid"
  },
  {
    nr:"481",
    naam:"Mesprit",
    type:"Psychisch",
    soort:"Emotie"
  },
  {
    nr:"482",
    naam:"Azelf",
    type:"Psychisch",
    soort:"Wils kracht"
  },
  {
    nr:"483",
    naam:"Dialga",
    type:"Staal/Draak",
    soort:"Tijd"
  },
  {
    nr:"484",
    naam:"Palkia",
    type:"Water/Draak",
    soort:"Ruimte"
  },
  {
    nr:"485",
    naam:"Heatran",
    type:"Vuur/Staal",
    soort:"Lava koepel"
  },
  {
    nr:"486",
    naam:"Regigigas",
    type:"Gewoon",
    soort:"Kossosaal"
  },
  {
    nr:"487",
    naam:"Giratina",
    type:"Spook/Draak",
    soort:"Renegaat"
  },
  {
    nr:"488",
    naam:"Cresselia",
    type:"Psychisch",
    soort:"Maan"
  },
  {
    nr:"489",
    naam:"Phione",
    type:"Water",
    soort:"Zeezwerver"
  },
  {
    nr:"490",
    naam:"Manaphy",
    type:"Water",
    soort:"Zeevarend"
  },
  {
    nr:"491",
    naam:"Darkrai",
    type:"Donker",
    soort:"Pikzwart"
  },
  {
    nr:"492",
    naam:"Shaymin",
    type:"Gras",
    soort:"Dankbaarheid"
  },
  {
    nr:"493",
    naam:"Arceus",
    type:"Gewoon",
    soort:"Alfa"
  },
  {
    nr:"494",
    naam:"Victini",
    type:"Psycho/Vuur",
    soort:"Overwinning"
  },
  {
    nr:"495",
    naam:"Snivy",
    type:"Gras",
    soort:"Gras slang"
  },
  {
    nr:"496",
    naam:"Servine",
    type:"Gras",
    soort:"Gras slang"
  },
  {
    nr:"497",
    naam:"Serperior",
    type:"Gras",
    soort:"Vorstelijk"
  },
  {
    nr:"498",
    naam:"Tepig",
    type:"Vuur",
    soort:"Vuurvarken"
  },
  {
    nr:"499",
    naam:"Pignite",
    type:"Vuur/Vecht",
    soort:"Vuurvarken"
  },
  {
    nr:"500",
    naam:"Emboar",
    type:"Vuur/Vecht",
    soort:"Groot vuurvarken"
  },
  {
    nr:"501",
    naam:"Oshawott",
    type:"Water",
    soort:"Zeeotter"
  },
  {
    nr:"502",
    naam:"Dewott",
    type:"Water",
    soort:"Discipline"
  },
  {
    nr:"503",
    naam:"Samurott",
    type:"Water",
    soort:"Geducht"
  },
  {
    nr:"504",
    naam:"Patrat",
    type:"Normaal",
    soort:"Verkenning"
  },
  {
    nr:"505",
    naam:"Watchog",
    type:"Normaal",
    soort:"Uitkijk"
  },
  {
    nr:"506",
    naam:"Lillipup",
    type:"Normaal",
    soort:"Puppy"
  },
  {
    nr:"507",
    naam:"Herdier",
    type:"Normaal",
    soort:"Trouwe Hond"
  },
  {
    nr:"508",
    naam:"Stoutland",
    type:"Normaal",
    soort:"Een groot hart"
  },
  {
    nr:"509",
    naam:"Purrloin",
    type:"Donker",
    soort:"Omslachtig"
  },
  {
    nr:"510",
    naam:"Liepard",
    type:"Donker",
    soort:"Wreed"
  },
  {
    nr:"511",
    naam:"Pansage",
    type:"Gras",
    soort:"Grasaap"
  },
  {
    nr:"512",
    naam:"Simisage",
    type:"Gras",
    soort:"Doornaap"
  },
  {
    nr:"513",
    naam:"Pansear",
    type:"Vuur",
    soort:"Hoge temperatuur"
  },
  {
    nr:"514",
    naam:"Simisear",
    type:"Vuur",
    soort:"Gloeiend"
  },
  {
    nr:"515",
    naam:"Panpour",
    type:"Water",
    soort:"Sproeier"
  },
  {
    nr:"516",
    naam:"Simipour",
    type:"Water",
    soort:"Geiser"
  },
  {
    nr:"517",
    naam:"Munna",
    type:"Psycho",
    soort:"Dromen eter"
  },
  {
    nr:"518",
    naam:"Musharna",
    type:"Psycho",
    soort:"Dommelen"
  },
  {
    nr:"519",
    naam:"Pidove",
    type:"Normaal/Vlieg",
    soort:"Kleine duif"
  },
  {
    nr:"520",
    naam:"Tranquill",
    type:"Normaal/Vlieg",
    soort:"Wilde duif"
  },
  {
    nr:"521",
    naam:"Unfezant",
    type:"Normaal/Vlieg",
    soort:"Trots"
  },
  {
    nr:"522",
    naam:"Blitzle",
    type:"Elektro",
    soort:"Geëlektrificeerd"
  },
  {
    nr:"523",
    naam:"Zebstrika",
    type:"Elektro",
    soort:"Bliksemflits"
  },
  {
    nr:"524",
    naam:"Roggenrola",
    type:"Steen",
    soort:"Dekmantel"
  },
  {
    nr:"525",
    naam:"Boldore",
    type:"Steen",
    soort:"Erts"
  },
  {
    nr:"526",
    naam:"Gigalith",
    type:"Steen",
    soort:"Gecomprimeerd"
  },
  {
    nr:"527",
    naam:"Woobat",
    type:"Psycho/Vlieg",
    soort:"Vleermuis"
  },
  {
    nr:"528",
    naam:"Swoobat",
    type:"Psycho/Vlieg",
    soort:"Verliefd"
  },
  {
    nr:"529",
    naam:"Drilbur",
    type:"Grond",
    soort:"Mol"
  },
  {
    nr:"530",
    naam:"Excadrill",
    type:"Grond/Staal",
    soort:"Subterrene"
  },
  {
    nr:"531",
    naam:"Audino",
    type:"Normaal",
    soort:"Gehoor"
  },
  {
    nr:"532",
    naam:"Timburr",
    type:"Vecht",
    soort:"Gespierd"
  },
  {
    nr:"533",
    naam:"Gurdurr",
    type:"Vecht",
    soort:"Gespierd"
  },
  {
    nr:"534",
    naam:"Conkeldurr",
    type:"Vecht",
    soort:"Gespierd"
  },
  {
    nr:"535",
    naam:"Tympole",
    type:"Water",
    soort:"Kikkervisje"
  },
  {
    nr:"536",
    naam:"Palpitoad",
    type:"Water/Grond",
    soort:"Trillingen"
  },
  {
    nr:"537",
    naam:"Seismitoad",
    type:"Water/Grond",
    soort:"Trillingen"
  },
  {
    nr:"538",
    naam:"Throh",
    type:"Vecht",
    soort:"Judo"
  },
  {
    nr:"539",
    naam:"Sawk",
    type:"Vecht",
    soort:"Karate"
  },
  {
    nr:"540",
    naam:"Sewaddle",
    type:"Insect/Gras",
    soort:"Zijderups"
  },
  {
    nr:"541",
    naam:"Swadloon",
    type:"Insect/Gras",
    soort:"In bladeren gewikkeld"
  },
  {
    nr:"542",
    naam:"Leavanny",
    type:"Insect/Gras",
    soort:"Verzorgend"
  },
  {
    nr:"543",
    naam:"Venipede",
    type:"Insect/Gif",
    soort:"Duizendpoot"
  },
  {
    nr:"544",
    naam:"Whirlipede",
    type:"Insect/Gif",
    soort:"Gedraaide duizendpoot"
  },
  {
    nr:"545",
    naam:"Scolipede",
    type:"Insect/Gif",
    soort:"Reuze duizendpoot"
  },
  {
    nr:"546",
    naam:"Cottonee",
    type:"Gras",
    soort:"Katoen-wind"
  },
  {
    nr:"547",
    naam:"Whimsicott",
    type:"Gras",
    soort:"Harde wind"
  },
  {
    nr:"548",
    naam:"Petilil",
    type:"Gras",
    soort:"Bol"
  },
  {
    nr:"549",
    naam:"Lilligant",
    type:"Gras",
    soort:"Bloeiend"
  },
  {
    nr:"550",
    naam:"Basculin",
    type:"Water",
    soort:"Vijandig"
  },
  {
    nr:"551",
    naam:"Sandile",
    type:"Grond/Donker",
    soort:"Woestijnkrokodil"
  },
  {
    nr:"552",
    naam:"Krokorok",
    type:"Grond/Donker",
    soort:"Woestijnkrokodil"
  },
  {
    nr:"553",
    naam:"Krookodile",
    type:"Grond/Donker",
    soort:"Intimidatie"
  },
  {
    nr:"554",
    naam:"Darumaka",
    type:"Vuur",
    soort:"Zen charme"
  },
  {
    nr:"555",
    naam:"Darmanitan",
    type:"Vuur",
    soort:"Brandend"
  },
  {
    nr:"556",
    naam:"Maractus",
    type:"Gras",
    soort:"Cactus"
  },
  {
    nr:"557",
    naam:"Dwebble",
    type:"Insect/Steen",
    soort:"Stenen huisje"
  },
  {
    nr:"558",
    naam:"Crustle",
    type:"Insect/Steen",
    soort:"Stenen flat"
  },
  {
    nr:"559",
    naam:"Scraggy",
    type:"Donker/Vecht",
    soort:"Plenging"
  },
  {
    nr:"560",
    naam:"Scrafty",
    type:"Donker/Vecht",
    soort:"Gangster"
  },
  {
    nr:"561",
    naam:"Sigilyph",
    type:"Psycho/Vlieg",
    soort:"Aviare"
  },
  {
    nr:"562",
    naam:"Yamask",
    type:"Spook",
    soort:"Spiritus"
  },
  {
    nr:"563",
    naam:"Cofagrigus",
    type:"Spook",
    soort:"Sarcofaag"
  },
  {
    nr:"564",
    naam:"Tirtouga",
    type:"Water/Steen",
    soort:"Protoschildpad"
  },
  {
    nr:"565",
    naam:"Carracosta",
    type:"Water/Steen",
    soort:"Protoschildpad"
  },
  {
    nr:"566",
    naam:"Archen",
    type:"Steen/Vlieg",
    soort:"Eerste vogel"
  },
  {
    nr:"567",
    naam:"Archeops",
    type:"Steen/Vlieg",
    soort:"Eerste vogel"
  },
  {
    nr:"568",
    naam:"Trubbish",
    type:"Gif",
    soort:"Afvalzak"
  },
  {
    nr:"569",
    naam:"Garbodor",
    type:"Gif",
    soort:"Stortplaats"
  },
  {
    nr:"570",
    naam:"Zorua",
    type:"Donker",
    soort:"Lastige vos"
  },
  {
    nr:"571",
    naam:"Zoroark",
    type:"Donker",
    soort:"Illusie-vos"
  },
  {
    nr:"572",
    naam:"Minccino",
    type:"Normaal",
    soort:"Chinchilla"
  },
  {
    nr:"573",
    naam:"Cinccino",
    type:"Normaal",
    soort:"Sjaal"
  },
  {
    nr:"574",
    naam:"Gothita",
    type:"Psycho",
    soort:"Vastleggen"
  },
  {
    nr:"575",
    naam:"Gothorita",
    type:"Psycho",
    soort:"Manipuleren"
  },
  {
    nr:"576",
    naam:"Gothitelle",
    type:"Psycho",
    soort:"Astraal lichaam"
  },
  {
    nr:"577",
    naam:"Solosis",
    type:"Psycho",
    soort:"Cel"
  },
  {
    nr:"578",
    naam:"Duosion",
    type:"Psycho",
    soort:"Celdeling"
  },
  {
    nr:"579",
    naam:"Reuniclus",
    type:"Psycho",
    soort:"Vermenigvuldigen"
  },
  {
    nr:"580",
    naam:"Ducklett",
    type:"Water/Vlieg",
    soort:"Water eendje"
  },
  {
    nr:"581",
    naam:"Swanna",
    type:"Water/Vlieg",
    soort:"Witte zwaan"
  },
  {
    nr:"582",
    naam:"Vanillite",
    type:"IJs",
    soort:"Frisse sneeuw"
  },
  {
    nr:"583",
    naam:"Vanillish",
    type:"IJs",
    soort:"IJzig sneeuw"
  },
  {
    nr:"584",
    naam:"Vanilluxe",
    type:"IJs",
    soort:"Sneeuwstorm"
  },
  {
    nr:"585",
    naam:"Deerling",
    type:"Normaal/Gras",
    soort:"Seizoen"
  },
  {
    nr:"586",
    naam:"Sawsbuck",
    type:"Normaal/Gras",
    soort:"Seizoen"
  },
  {
    nr:"587",
    naam:"Emolga",
    type:"Eletkro/Vlieg",
    soort:"Vliegende eekhoorn"
  },
  {
    nr:"588",
    naam:"Karrablast",
    type:"Insect",
    soort:"Klemmen"
  },
  {
    nr:"589",
    naam:"Escavalier",
    type:"Insect/Staal",
    soort:"Ruiterij"
  },
  {
    nr:"590",
    naam:"Foongus",
    type:"Gras/Gif",
    soort:"Paddenstoel"
  },
  {
    nr:"591",
    naam:"Amoonguss",
    type:"Gras/Gif",
    soort:"Paddenstoel"
  },
  {
    nr:"592",
    naam:"Frillish",
    type:"Water/Spook",
    soort:"Zwevend"
  },
  {
    nr:"593",
    naam:"Jellicent",
    type:"Water/Spook",
    soort:"Zwevend"
  },
  {
    nr:"594",
    naam:"Alomomola",
    type:"Water",
    soort:"Zorgend"
  },
  {
    nr:"595",
    naam:"Joltik",
    type:"Insect/Electro",
    soort:"Vastmaken"
  },
  {
    nr:"596",
    naam:"Galvantula",
    type:"Insect/Electro",
    soort:"Elektrische spin"
  },
  {
    nr:"597",
    naam:"Ferroseed",
    type:"Gras/Staal",
    soort:"Doorn zaad"
  },
  {
    nr:"598",
    naam:"Ferrothorn",
    type:"Gras/Staal",
    soort:"Doorn huls"
  },
  {
    nr:"599",
    naam:"Klink",
    type:"Staal",
    soort:"Tandwiel"
  },
  {
    nr:"600",
    naam:"Klang",
    type:"Staal",
    soort:"Tandwiel"
  },
  {
    nr:"601",
    naam:"Klinklang",
    type:"Staal",
    soort:"Tandwiel"
  },
  {
    nr:"602",
    naam:"Tynamo",
    type:"Elektro",
    soort:"Elektrische vis"
  },
  {
    nr:"603",
    naam:"Electrik",
    type:"Elektro",
    soort:"Elektrische vis"
  },
  {
    nr:"604",
    naam:"Elektross",
    type:"Elektro",
    soort:"Elektrische vis"
  },
  {
    nr:"605",
    naam:"Elgyem",
    type:"Psycho",
    soort:"Hersenen"
  },
  {
    nr:"606",
    naam:"Beheeyem",
    type:"Psycho",
    soort:"Hersenen"
  },
  {
    nr:"607",
    naam:"Litwick",
    type:"Spook/Vuur",
    soort:"Kaars"
  },
  {
    nr:"608",
    naam:"Lampent",
    type:"Spook/Vuur",
    soort:"Lamp"
  },
  {
    nr:"609",
    naam:"Chandelure",
    type:"Spook/Vuur",
    soort:"Lokken"
  },
  {
    nr:"610",
    naam:"Axew",
    type:"Draak",
    soort:"Slagtand"
  },
  {
    nr:"611",
    naam:"Fraxure",
    type:"Draak",
    soort:"Hak-kaak"
  },
  {
    nr:"612",
    naam:"Haxorus",
    type:"Draak",
    soort:"Hak-kaak"
  },
  {
    nr:"613",
    naam:"Cubchoo",
    type:"IJs",
    soort:"Kilte"
  },
  {
    nr:"614",
    naam:"Beartic",
    type:"IJs",
    soort:"Vriezend"
  },
  {
    nr:"615",
    naam:"Cryogonal",
    type:"IJs",
    soort:"Kristalliserend"
  },
  {
    nr:"616",
    naam:"Shelmet",
    type:"Insect",
    soort:"Slak"
  },
  {
    nr:"617",
    naam:"Accelgor",
    type:"Insect",
    soort:"Uit de schelp"
  },
  {
    nr:"618",
    naam:"Stunfisk",
    type:"Grond/Electro",
    soort:"Valstrik"
  },
  {
    nr:"619",
    naam:"Mienfoo",
    type:"Vecht",
    soort:"Vechtsport"
  },
  {
    nr:"620",
    naam:"Mienshao",
    type:"Vecht",
    soort:"Vechtsport"
  },
  {
    nr:"621",
    naam:"Druddigon",
    type:"Draak",
    soort:"Grot"
  },
  {
    nr:"622",
    naam:"Golett",
    type:"Grond/Spook",
    soort:"Automaat"
  },
  {
    nr:"623",
    naam:"Golurk",
    type:"Grond/Spook",
    soort:"Automaat"
  },
  {
    nr:"624",
    naam:"Pawniard",
    type:"Donker/Staal",
    soort:"Scherpe messen"
  },
  {
    nr:"625",
    naam:"Bisharp",
    type:"Donker/Staal",
    soort:"Scherpe zwaarden"
  },
  {
    nr:"626",
    naam:"Bouffalant",
    type:"Normaal",
    soort:"Slag buffel"
  },
  {
    nr:"627",
    naam:"Rufflet",
    type:"Normaal/Vlieg",
    soort:"Jonge arend"
  },
  {
    nr:"628",
    naam:"Braviary",
    type:"Normaal/Vlieg",
    soort:"Dapper"
  },
  {
    nr:"629",
    naam:"Vullaby",
    type:"Donker/Vlieg",
    soort:"Luur"
  },
  {
    nr:"630",
    naam:"Mandibuzz",
    type:"Donker/Vlieg",
    soort:"Botten gier"
  },
  {
    nr:"631",
    naam:"Heatmor",
    type:"Vuur",
    soort:"Miereneter"
  },
  {
    nr:"632",
    naam:"Durant",
    type:"Insect/Staal",
    soort:"Metalen mier"
  },
  {
    nr:"633",
    naam:"Deino",
    type:"Donker/Draak",
    soort:"Verbolgen"
  },
  {
    nr:"634",
    naam:"Zweilous",
    type:"Donker/Draak",
    soort:"Vijandig"
  },
  {
    nr:"635",
    naam:"Hydreigon",
    type:"Donker/Draak",
    soort:"Wreed"
  },
  {
    nr:"636",
    naam:"Larvesta",
    type:"Insect/Vuur",
    soort:"Fakkel"
  },
  {
    nr:"637",
    naam:"Volcarona",
    type:"Insect/Vuur",
    soort:"Zon"
  },
  {
    nr:"638",
    naam:"Cobalion",
    type:"Staal/Vecht",
    soort:"Stalen wil"
  },
  {
    nr:"639",
    naam:"Terrakion",
    type:"Steen/Vecht",
    soort:"Kracht"
  },
  {
    nr:"640",
    naam:"Virizion",
    type:"Gras/Vecht",
    soort:"Grasland"
  },
  {
    nr:"641",
    naam:"Tornadus",
    type:"Vlieg",
    soort:"Cycloon"
  },
  {
    nr:"642",
    naam:"Thundurus",
    type:"Elektro/Vlieg",
    soort:"Donder treffing"
  },
  {
    nr:"643",
    naam:"Reshiram",
    type:"Draak/Vuur",
    soort:"Royaal wit"
  },
  {
    nr:"644",
    naam:"Zekrom",
    type:"Draak/Elektro",
    soort:"Diep zwart"
  },
  {
    nr:"645",
    naam:"Landorus",
    type:"Grond/Vlieg",
    soort:"Overvloed"
  },
  {
    nr:"646",
    naam:"Kyurem",
    type:"Draak/IJs",
    soort:"Grens"
  },
  {
    nr:"647",
    naam:"Keldeo",
    type:"Water/Vecht",
    soort:"Jonge hengst"
  },
  {
    nr:"648",
    naam:"Meloetta",
    type:"Gewoon/Psycho",
    soort:"Melodie"
  },
  {
    nr:"649",
    naam:"Genesect",
    type:"Insect/Staal",
    soort:"Paleozoïcum"
  }]